[Interface]
# Bouncing = 0
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = MEok4nxfpsgt9Zj7p6okqqgYN65Oartn0vGg5USsZHQ=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# MX-FREE#3
PublicKey = rNyiLhJsBGoHd0A6Yrzt6c5DHuD3urE5+ZN3DZITfD8=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 149.102.224.33:51820

PersistentKeepalive = 25