[Interface]
# Bouncing = 9
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = YLuHOJZ+mWyHCOvBhXV0HiSvoDxbnqqyoXPA3QdRaVw=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# RO-FREE#23
PublicKey = ehwHh3WXBDwFxqTs4Oa8aZZYjOnd3NwjbMArKRwTqzs=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 146.70.246.98:51820

PersistentKeepalive = 25