[Interface]
# Bouncing = 3
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = 4OqquR6RF9y5WXnvBJXlDEx539LaBwyJWV9nyJRoVVc=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# SG-FREE#6
PublicKey = AMrYsHq/kc8SLUxR5Z9OXuNCcF9YvsOl9Ch60hc+Q2U=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 149.50.211.134:51820

PersistentKeepalive = 25