[Interface]
# Bouncing = 2
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = MIsU37DY6XDRSLQHTq82jzzJ3YkT1ExFEvwNEqfn1W0=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# CH-FREE#10
PublicKey = 1WO+SU1kJCYR5ZWBVK/M7bNsvz1HWIFlq/xafhDqHnk=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 135.136.39.2:51820

PersistentKeepalive = 25